/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Transaction_Druges;
import Entity.TransactionsReport;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;
import pharmacysystem.Tool;
import pharmacysystem.Tool.Table;

/**
 *
 * @author hp-
 */
public class frmTransactionReport extends javax.swing.JFrame {

    /**
     * Creates new form frmTransactionReport
     */
    
    int uID;
    String Uname;
    String type;
    
    public frmTransactionReport(int userID, String username, String type) {
        initComponents();
        this.uID = userID;
        this.Uname = username;
        this.type = type;
    }

    private frmTransactionReport() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransReports = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbxTransReports = new controls.JMyCombBox();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltransdrugsreport = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblTransReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "TransID", "UserID", "CustomerName", "CustomerPhone", "TotalPrice", "TransTime", "ReportTime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransReports.getTableHeader().setReorderingAllowed(false);
        tblTransReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransReportsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransReports);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Transaction Report");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbxTransReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTransReportsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel10.setText("Reports:");

        tbltransdrugsreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltransdrugsreport.getTableHeader().setResizingAllowed(false);
        tbltransdrugsreport.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbltransdrugsreport);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setText("Drug Info:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addGap(46, 46, 46)
                        .addComponent(cbxTransReports, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(436, 436, 436))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTransReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(74, 74, 74))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tool.openForm(new frmDrug_TranReport(this.uID, this.Uname, this.type));
    }//GEN-LAST:event_btnBackActionPerformed
    TransactionsReport TReport = new TransactionsReport();
    private void cbxTransReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTransReportsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)tblTransReports.getModel();
        model.setNumRows(0);
        String report = cbxTransReports.getSelectedItem().toString();
        int reportID = Integer.parseInt(report.replaceAll("[^0-9]", ""));
        Table t = DB.db.getTableData("select * from transactionreport where reportid = " + reportID);

        for (int i = 0 ; i < t.Items.length ; i++){
            model.addRow(new Object[]{t.Items[i][0], t.Items[i][1], t.Items[i][2], t.Items[i][3],
                t.Items[i][4], t.Items[i][5], t.Items[i][6], t.Items[i][7]});
        }

    }//GEN-LAST:event_cbxTransReportsActionPerformed
    private static long getDateDiff(String start_date, String end_date, TimeUnit timeUnit) throws ParseException {
        
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
         
         Date d1 = sdf.parse(start_date); 
         Date d2 = sdf.parse(end_date);
         long diffInMillies = d2.getTime() - d1.getTime();
         
         return timeUnit.convert(diffInMillies,TimeUnit.MILLISECONDS);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
//        try {
//            
//        int start = 0;
//        int firstID = 0;
//        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
//        SimpleDateFormat f1 = new SimpleDateFormat("yyyy-MM-dd");
//        String Cpoint2 = " 17:00:00";
//        
//        String str = "select reftime from user where userid = 1";
//        Tool.Table t = DB.db.getTableData(str);
//        
//        String refTime = (String)t.Items[0][0]; // 2021-01-01 00:00:00
//        Date ref = f.parse(refTime);
//        Date d = new Date();
//        String currentTime = f.format(d);
//        
//        long noOfHours = getDateDiff(refTime, currentTime, TimeUnit.HOURS);
//                   
//        for (int i = 0 ; i < noOfHours; i++){
//            ref.setHours(ref.getHours()+1);
//            
//            if (ref.getHours() == 17){
//                String sqlstr = "select * from transaction where time <= '" + f1.format(ref) + Cpoint2 + "'";
//                Tool.Table t2 = DB.db.getTableData(sqlstr);
//                if (t2.Items.length != 0){
//                   String autonum = TReport.getAutoNumber();
//                   TReport.setReportID(Integer.parseInt(autonum));
//                   TReport.setTime(f1.format(ref) + Cpoint2);
//                   TReport.addTransReport(sqlstr);
//                   
//                   String strUpdate = "update user set " + "reftime = '" + f.format(ref) +"' where userid = 1";
//                   DB.db.runNonQuery(strUpdate);
//                   
//                   if (start == 0){
//                      firstID =  Integer.parseInt(autonum);
//                      start = 1;
//                   }
//                }
//            }
//        }
//          
//        DB.db.fillComb("transactionreport", "reportid", cbxTransReports);
//        if (start != 0){
//            cbxTransReports.setSelectedItem("Report " + firstID);
//            System.out.println(firstID);
//        }
//
//        } catch (ParseException ex) {
//            Tool.msgBox(ex.getMessage());
//        }

        DB.db.fillComb("transactionreport", "reportid", cbxTransReports);
        String str = "select firsttran from user where userid = 1";
        Table tb = DB.db.getTableData(str);
        int reportid = Integer.parseInt((String)tb.Items[0][0]);
        if (reportid != 0){
           cbxTransReports.setSelectedItem("Report " + reportid);
           String strUpdate = "update user set " + "firsttran = 0 where userid = 1";
           DB.db.runNonQuery(strUpdate);
        }
        
        
    }//GEN-LAST:event_formWindowOpened
    Transaction_Druges trandrug = new Transaction_Druges();
    
    private void tblTransReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransReportsMouseClicked
        // TODO add your handling code here:
        int row = tblTransReports.getSelectedRow();
        String strtranid = tblTransReports.getValueAt(row, 1).toString();

        trandrug.setTranID(Integer.parseInt(strtranid));
        trandrug.getAllRows(tbltransdrugsreport);
    }//GEN-LAST:event_tblTransReportsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransactionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransactionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransactionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransactionReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransactionReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnBack;
    private controls.JMyCombBox cbxTransReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblTransReports;
    private javax.swing.JTable tbltransdrugsreport;
    // End of variables declaration//GEN-END:variables
}
