/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Drug;
import Entity.Transaction;
import Entity.Transaction_Druges;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import pharmacysystem.Tool;

/**
 *
 * @author hp-
 */
public class frmTransaction extends javax.swing.JFrame {

    /**
     * Creates new form frmTransaction
     */
    int uID;
    String Uname;
    String type;
    public frmTransaction(int userID, String username, String type) {
        initComponents();
        this.uID = userID;
        this.Uname = username;
        this.type = type;
    }

    private frmTransaction() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnremovedrug = new controls.JMyButton();
        jSeparator3 = new javax.swing.JSeparator();
        btndeldrug = new controls.JMyButton();
        jSeparator1 = new javax.swing.JSeparator();
        txttranid = new controls.JTextBox(15);
        txtuserid = new controls.JTextBox(15);
        txtcustomerName = new controls.JTextBox(15);
        txtcustomerPhone = new controls.JTextBox(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltrans = new javax.swing.JTable();
        cbxdrugs = new controls.JMyCombBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldrugs_sold = new javax.swing.JTable();
        btnadd = new controls.JMyButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnadddrug = new controls.JMyButton();
        txttotalprice = new controls.JTextBox(15);
        jLabel7 = new javax.swing.JLabel();
        txtamount_sold = new controls.JTextBox(15);
        btnclear = new controls.JMyButton();
        btnclaculate = new controls.JMyButton();
        lblinfo = new javax.swing.JLabel();
        btnBack = new controls.JMyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnremovedrug.setText("Remove");
        btnremovedrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnremovedrugMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnremovedrugMouseExited(evt);
            }
        });
        btnremovedrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremovedrugActionPerformed(evt);
            }
        });

        btndeldrug.setText("Del");
        btndeldrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndeldrugMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndeldrugMouseExited(evt);
            }
        });
        btndeldrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeldrugActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txttranid.setEditable(false);
        txttranid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttranidActionPerformed(evt);
            }
        });

        txtuserid.setEditable(false);

        txtcustomerPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomerPhoneActionPerformed(evt);
            }
        });

        tbltrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "User ID", "Customer Name", "Customer Phone", "Total Price", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltrans.getTableHeader().setResizingAllowed(false);
        tbltrans.getTableHeader().setReorderingAllowed(false);
        tbltrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltransMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltrans);

        cbxdrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdrugsActionPerformed(evt);
            }
        });

        tbldrugs_sold.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldrugs_sold.getTableHeader().setResizingAllowed(false);
        tbldrugs_sold.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbldrugs_sold);

        btnadd.setText("Add");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddMouseExited(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Transaction Form");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel2.setText("Number:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setText("User ID:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel4.setText("Customer Name:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel5.setText("Customer Phone:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel6.setText("Total Price:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel10.setText("Drugs:");

        btnadddrug.setText("Add");
        btnadddrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnadddrugMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnadddrugMouseExited(evt);
            }
        });
        btnadddrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadddrugActionPerformed(evt);
            }
        });

        txttotalprice.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel7.setText("Amount:");

        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclearMouseExited(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnclaculate.setText("calculate");
        btnclaculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclaculateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclaculateMouseExited(evt);
            }
        });
        btnclaculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclaculateActionPerformed(evt);
            }
        });

        lblinfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(68, 68, 68)
                                .addComponent(txttranid, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(71, 71, 71)
                                .addComponent(txtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)
                                .addComponent(txtcustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)
                                .addComponent(txtcustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(70, 70, 70)
                                .addComponent(txtamount_sold, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(31, 31, 31)
                                    .addComponent(txttotalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnclaculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnadddrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(19, 19, 19)
                                            .addComponent(btndeldrug, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnremovedrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxdrugs, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(445, 445, 445))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txttranid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtcustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel5))
                                    .addComponent(txtcustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(cbxdrugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(lblinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtamount_sold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnadddrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btndeldrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addComponent(btnremovedrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttotalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnclaculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Transaction trans = new Transaction();
    Transaction_Druges trandrug = new Transaction_Druges();
    Drug drug = new Drug();
            
    private void btnremovedrugMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremovedrugMouseEntered
        // TODO add your handling code here:
        //this.btnremovedrug.setSize(150,35);
    }//GEN-LAST:event_btnremovedrugMouseEntered

    private void btnremovedrugMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremovedrugMouseExited
        // TODO add your handling code here:
        //this.btnremovedrug.setSize(135,26);
    }//GEN-LAST:event_btnremovedrugMouseExited

    private void btnremovedrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremovedrugActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbldrugs_sold.getModel();
        model.setNumRows(0);
        lblinfo.setText("");
    }//GEN-LAST:event_btnremovedrugActionPerformed

    private void btndeldrugMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeldrugMouseEntered
        // TODO add your handling code here:
        //this.btndeldrug.setSize(70,30);
    }//GEN-LAST:event_btndeldrugMouseEntered

    private void btndeldrugMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeldrugMouseExited
        // TODO add your handling code here:
        //this.btndeldrug.setSize(56,26);
    }//GEN-LAST:event_btndeldrugMouseExited

    private void btndeldrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeldrugActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbldrugs_sold.getModel();
        int a=tbldrugs_sold.getSelectedRow();
        int new_amount = Integer.parseInt(lblinfo.getText().replaceAll("[^0-9]", ""))+ Integer.parseInt(tbldrugs_sold.getValueAt(a, 1).toString());
        lblinfo.setText("<html>The Availabile Amount: <font color='blue'> "+String.valueOf(new_amount)+"</font>" +"</html>");
   
        model.removeRow(a);
    }//GEN-LAST:event_btndeldrugActionPerformed

    private void txttranidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttranidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttranidActionPerformed

    private void tbltransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltransMouseClicked
        try {
            // TODO add your handling code here:
            int row = tbltrans.getSelectedRow();
            String strtranid = tbltrans.getValueAt(row, 0).toString();
            String struserid = tbltrans.getValueAt(row, 1).toString();
            String customerName = tbltrans.getValueAt(row, 2).toString();
            String customerPhone = tbltrans.getValueAt(row, 3).toString();
            String Totalprice = tbltrans.getValueAt(row, 4).toString();
            

            txttranid.setText(strtranid);
            txtuserid.setText(struserid);
            txtcustomerName.setText(customerName);
            txtcustomerPhone.setText(customerPhone);
            txttotalprice.setText(Totalprice);
            
            

            trandrug.setTranID(Integer.parseInt(txttranid.getText()));
            trandrug.getAllRows(tbldrugs_sold);

            btnadd.setEnabled(false);

        } catch (Exception ex) {
            Tool.msgBox(ex.getMessage());
        }

    }//GEN-LAST:event_tbltransMouseClicked

    private void btnaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseEntered
        // TODO add your handling code here:
        //this.btnadd.setSize(180,50);
    }//GEN-LAST:event_btnaddMouseEntered

    private void btnaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseExited
        // TODO add your handling code here:
        //this.btnadd.setSize(170,37);
    }//GEN-LAST:event_btnaddMouseExited
    private void setValues(){
        trans.setTranID(Integer.parseInt(txttranid.getText()));
        trans.setUserID(Integer.parseInt(txtuserid.getText()));
        trans.setCustomerName(txtcustomerName.getText());
        trans.setCustomerPhone(txtcustomerPhone.getText());
        trans.setTotalPrice(Double.parseDouble(txttotalprice.getText()));
        
        SimpleDateFormat f1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date dnow =new Date();
        trans.setTime(f1.format(dnow));
        
    }
    
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
 
        DefaultTableModel model = (DefaultTableModel)tbldrugs_sold.getModel();
        setValues();
        trans.add();
        trandrug.setTranID(Integer.parseInt(txttranid.getText()));
                
        for (int x=0 ; x < tbldrugs_sold.getRowCount() ; x++){
            int Dcode = Integer.parseInt(drug.getValueByName(tbldrugs_sold.getValueAt(x, 0).toString()));
            int amount_sold = Integer.parseInt(tbldrugs_sold.getValueAt(x, 1).toString());
            trandrug.setDrugName(tbldrugs_sold.getValueAt(x, 0).toString());
            trandrug.setDrugCode(Dcode);
            trandrug.setAmount(Integer.parseInt(tbldrugs_sold.getValueAt(x, 1).toString()));
            trandrug.add();
            
            String select = "select amount from drug" + " where drugcode = " + Dcode;
            int old_amount = Integer.parseInt((String)DB.db.getTableData(select).Items[0][0]);
            int new_amount = old_amount - amount_sold;
            String strUpdate = "update drug set " + "amount = " + new_amount +" where drugcode = " + Dcode;
            DB.db.runNonQuery(strUpdate);
        }
        model.setNumRows(0);
        clearData();
        trans.getAllRows(tbltrans);
                                    

    }//GEN-LAST:event_btnaddActionPerformed

    private void btnadddrugMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadddrugMouseEntered
        // TODO add your handling code here:
        //this.btnadddrug.setSize(70,30);
    }//GEN-LAST:event_btnadddrugMouseEntered

    private void btnadddrugMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadddrugMouseExited
        // TODO add your handling code here:
        //this.btnadddrug.setSize(56,26);
    }//GEN-LAST:event_btnadddrugMouseExited

    private void btnadddrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadddrugActionPerformed
        // TODO add your handling code here:
      
       DefaultTableModel model = (DefaultTableModel)tbldrugs_sold.getModel();
       model.addRow(new Object[]{cbxdrugs.getSelectedItem().toString(),txtamount_sold.getText()});
       int new_amount = Integer.parseInt(lblinfo.getText().replaceAll("[^0-9]", ""))- Integer.parseInt(txtamount_sold.getText());
       lblinfo.setText("<html>The Availabile Amount: <font color='blue'> "+String.valueOf(new_amount)+"</font>" +"</html>");
       txtamount_sold.setText("");
       txtamount_sold.requestFocus();

    }//GEN-LAST:event_btnadddrugActionPerformed

    private void txtcustomerPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomerPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomerPhoneActionPerformed
    private void clearData(){
        Tool.clearText(this);
        txttranid.setText(trans.getAutoNumber());
        btnadd.setEnabled(true);
        txtuserid.setText(String.valueOf(uID));
        txtcustomerName.requestFocus();
        DefaultTableModel model = (DefaultTableModel)tbldrugs_sold.getModel();
        model.setNumRows(0);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DB.db.fillComb("drug", "drugname", cbxdrugs);
        
        trans.getAllRows(tbltrans);
        clearData();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseEntered
        // TODO add your handling code here:
        //this.btnclear.setSize(180,50);
    }//GEN-LAST:event_btnclearMouseEntered

    private void btnclearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseExited
        // TODO add your handling code here: 
        //this.btnclear.setSize(170,37);
    }//GEN-LAST:event_btnclearMouseExited

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnclaculateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclaculateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclaculateMouseEntered

    private void btnclaculateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclaculateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclaculateMouseExited

    private void btnclaculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclaculateActionPerformed
        // TODO add your handling code here:
        double totalprice = 0;
        for (int x=0 ; x < tbldrugs_sold.getRowCount() ; x++){
            String drugName = tbldrugs_sold.getValueAt(x, 0).toString();
            int Dcode = Integer.parseInt(drug.getValueByName(drugName));
            int amount_sold = Integer.parseInt(tbldrugs_sold.getValueAt(x, 1).toString());
            
            String select = "select price from drug" + " where drugcode = " + Dcode;
            double price = Double.parseDouble((String)DB.db.getTableData(select).Items[0][0]);
            totalprice = totalprice + amount_sold * price;
        }
        txttotalprice.setText(String.valueOf(totalprice));
    }//GEN-LAST:event_btnclaculateActionPerformed

    private void cbxdrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdrugsActionPerformed
        // TODO add your handling code here:
        String Dname = cbxdrugs.getSelectedItem().toString();
        int Dcode = Integer.parseInt(drug.getValueByName(Dname));
        
        String select = "select amount from drug" + " where drugcode = " + Dcode;
        int Available_amount = Integer.parseInt((String)DB.db.getTableData(select).Items[0][0]);
        
        lblinfo.setText("<html>The Availabile Amount: <font color='blue'> "+String.valueOf(Available_amount)+"</font>" +"</html>");
    }//GEN-LAST:event_cbxdrugsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (this.type.equals("Pharmacy Manager")){
            this.dispose();
            Tool.openForm(new frmManagerMain(this.uID, this.Uname, this.type));
        }
        else if (this.type.equals("Pharmacist")){
            this.dispose();
            Tool.openForm(new frmPharmacistMain(this.uID, this.Uname, this.type));
        }
        else {
            this.dispose();
            Tool.openForm(new frmCashierMain(this.uID, this.Uname, this.type));
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnBack;
    private controls.JMyButton btnadd;
    private controls.JMyButton btnadddrug;
    private controls.JMyButton btnclaculate;
    private controls.JMyButton btnclear;
    private controls.JMyButton btndeldrug;
    private controls.JMyButton btnremovedrug;
    private controls.JMyCombBox cbxdrugs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JTable tbldrugs_sold;
    private javax.swing.JTable tbltrans;
    private javax.swing.JTextField txtamount_sold;
    private javax.swing.JTextField txtcustomerName;
    private javax.swing.JTextField txtcustomerPhone;
    private javax.swing.JTextField txttotalprice;
    private javax.swing.JTextField txttranid;
    private javax.swing.JTextField txtuserid;
    // End of variables declaration//GEN-END:variables
}
